"""Added method_of_victory and round_ended to Game

Revision ID: 19f1b5607db6
Revises: 
Create Date: 2025-05-04 13:51:40.204845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19f1b5607db6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('method_of_victory', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('round_ended', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('round_ended')
        batch_op.drop_column('method_of_victory')

    # ### end Alembic commands ###
