"""Added API bet fields

Revision ID: 2472a8556ca4
Revises: 19f1b5607db6
Create Date: 2025-05-05 19:44:00.860681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2472a8556ca4'
down_revision = '19f1b5607db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('home_team', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('away_team', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('selection', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('odds', sa.Float(), nullable=True))
        batch_op.create_foreign_key('fk_bet_game_id', 'game', ['game_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('odds')
        batch_op.drop_column('selection')
        batch_op.drop_column('away_team')
        batch_op.drop_column('home_team')
        batch_op.drop_column('game_id')

    # ### end Alembic commands ###
